# Generated by Django 4.0 on 2022-02-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='1.jpg', null=True, upload_to=''),
        ),
    ]
