# Generated by Django 4.0 on 2022-02-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backpacker', '0002_package_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now=True)),
                ('price', models.IntegerField()),
                ('nos', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backpacker.agent')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backpacker.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backpacker.customuser')),
            ],
        ),
    ]
