# Generated by Django 4.0 on 2022-02-20 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backpacker', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backpacker.customuser'),
        ),
    ]
